//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace readerLib.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlData
    {
        public int DataId { get; set; }
        public string DeviceNumber { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
